import type { Analysis } from "./types";
import type { SentimentTimeline } from "./sentiment";
import type { Superfan } from "./superfans";

/**
 * The "State of the Audience" email: everything the report computed, composed
 * into one message a creator can paste into any newsletter tool or send to a
 * co-editor. Pure string building over already-computed data — the same
 * pattern as the editor handoff pack, and just as unit-testable. No model
 * writes this; every number in it was calculated upstream.
 */

export interface DigestInput {
  channelTitle: string;
  videoTitle: string;
  commentsAnalyzed: number;
  analysis: Analysis;
  sentiment?: SentimentTimeline;
  dips?: { timestamp: string; dropPercent: number; quote?: string }[];
  superfans?: Superfan[];
  /** Flagged scam/spam count from the latest patrol, if one ran. */
  patrolFlagged?: number;
  /** ISO date the digest covers up to; injected so tests are deterministic. */
  generatedAt: string;
}

export interface Digest {
  subject: string;
  markdown: string;
}

function themeCount(analysis: Analysis, name: string): number {
  return analysis.clusters.themes.find((t) => t.name === name)?.count ?? 0;
}

function sentimentWord(score: number): string {
  if (score > 0.25) return "warm";
  if (score > 0.12) return "leaning positive";
  if (score < -0.25) return "rough";
  if (score < -0.12) return "leaning negative";
  return "mixed";
}

export function buildAudienceDigest(input: DigestInput): Digest {
  const { analysis } = input;
  const date = input.generatedAt.slice(0, 10);
  const requests = themeCount(analysis, "request");
  const complaints = themeCount(analysis, "complaint");
  const praise = themeCount(analysis, "praise");
  const confusion = themeCount(analysis, "confusion");

  const lines: string[] = [];
  lines.push(`# State of the Audience — ${input.channelTitle}`);
  lines.push("");
  lines.push(
    `*${date} · built from ${input.commentsAnalyzed} comments on “${input.videoTitle}”. ` +
      `Every number below was computed, not generated.*`
  );
  lines.push("");

  lines.push(`## The week in one paragraph`);
  const mood = input.sentiment ? sentimentWord(input.sentiment.overall.score) : "mixed";
  lines.push(
    `The room is ${mood}: ${praise} comments praised, ${complaints} complained, ` +
      `${requests} asked for something specific, and ${confusion} got lost somewhere. ` +
      (analysis.clusters.summary || "")
  );
  lines.push("");

  if (input.dips && input.dips.length > 0) {
    const worst = [...input.dips].sort((a, b) => b.dropPercent - a.dropPercent)[0];
    lines.push(`## The number that matters`);
    lines.push(
      `**${worst.dropPercent}% of the audience leaves at ${worst.timestamp}.**` +
        (worst.quote ? ` A viewer explains why: “${worst.quote}”` : ` No comment explains it — the answer is in the footage.`)
    );
    lines.push("");
  }

  const topIdea = analysis.ideas[0];
  const topFix = analysis.fixes[0];
  lines.push(`## Do these this week`);
  if (topFix) lines.push(`1. **Fix:** ${topFix.fix} *(because: “${topFix.evidence_quote}”)*`);
  if (topIdea) {
    lines.push(
      `${topFix ? "2" : "1"}. **Make:** “${topIdea.title}” — ${topIdea.estimated_interest} interest, ` +
        `viewers are already asking: “${topIdea.evidence_quotes[0] ?? ""}”`
    );
  }
  if (input.patrolFlagged !== undefined) {
    lines.push(
      `${[topFix, topIdea].filter(Boolean).length + 1}. **Clean up:** ${input.patrolFlagged} scam/spam ` +
        `comment${input.patrolFlagged === 1 ? "" : "s"} flagged by the last patrol — hide them in one click.`
    );
  }
  lines.push("");

  if (input.superfans && input.superfans.length > 0) {
    lines.push(`## Who showed up`);
    for (const fan of input.superfans.slice(0, 5)) {
      const why = fan.badges.length > 0 ? ` — ${fan.badges.join(", ")}` : "";
      lines.push(`- **${fan.author}**${why}`);
    }
    lines.push("");
  }

  const quotes = analysis.clusters.themes
    .flatMap((t) => t.top_quotes.slice(0, 1).map((q) => ({ theme: t.name, quote: q })))
    .slice(0, 4);
  if (quotes.length > 0) {
    lines.push(`## In their words`);
    for (const q of quotes) lines.push(`- *(${q.theme})* “${q.quote}”`);
    lines.push("");
  }

  lines.push(`---`);
  lines.push(`*Generated by AudienceSignal from public comments and your own analytics.*`);

  return {
    subject: `State of the Audience — ${input.channelTitle} — ${date}`,
    markdown: lines.join("\n"),
  };
}
